### ISSUE TITLE
Perhaps update this to work with object desctructuring

### ISSUE THREAD

**Issue by the1mills** [bendrucker/require-deps#1]
Perhaps update this to work with object desctructuring / array destructuring?

**Comment by the1mills** [comment]
```js
const [babel, express, gulp] = requireDeps(['babel','express','gulp']);
```

**Comment by bendrucker** [comment]
That's not the purpose of this library. It's for generating code, not direct use like you've shown. It returns a string. You can't do dynamic module loading with browser bundlers since they depend on static analysis to detect dependencies.
